### ISSUE TITLE
Hard time getting it started

### ISSUE THREAD

**Issue by rycon2424** [cxong/wibblish#15]
Hey there im having a hard time getting the program started. As someone who is only familiar with exe's I have no clue how to start the programs up properly.

I see the 
"yarn"
"yarn run dev"
but have no clue where to type this or anything.

Any help? Thanks!

**Comment by cxong** [comment]
https://yarnpkg.com/getting-started

**Comment by rycon2424** [comment]
After running "yarn run dev" in the node.js cmd i got this error and this page which looks incomplete. Any ideas?

https://snipboard.io/vAqPRQ.jpg

**Comment by cxong** [comment]
reverted to an earlier, working version
